import React from 'react';

const Advantages = () => {
  return <div class="container">
  <h2>Advantages</h2>
  <h3>mauris a diam maecenas sed</h3>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pulvinar mattis nunc sed blandit libero volutpat sed cras ornare. Semper feugiat nibh sed pulvinar proin gravida hendrerit. Eu ultrices vitae auctor eu. Neque volutpat ac tincidunt vitae semper quis. Sit amet tellus cras adipiscing enim eu. Vel fringilla est ullamcorper eget nulla. At imperdiet dui accumsan sit amet nulla facilisi morbi tempus. Vel pretium lectus quam id. Consectetur libero id faucibus nisl tincidunt eget nullam non. Suspendisse interdum consectetur libero id faucibus nisl tincidunt eget nullam. Sed vulputate odio ut enim blandit. Iaculis nunc sed augue lacus viverra vitae. Risus feugiat in ante metus dictum. Hendrerit gravida rutrum quisque non tellus orci ac auctor. Sapien faucibus et molestie ac feugiat sed. Vestibulum sed arcu non odio euismod lacinia at.</p>
  
  <p>Dui sapien eget mi proin sed libero. Orci phasellus egestas tellus rutrum tellus pellentesque. Morbi tristique senectus et netus et. Gravida in fermentum et sollicitudin. Vel fringilla est ullamcorper eget nulla. Tincidunt lobortis feugiat vivamus at. Arcu odio ut sem nulla pharetra. Eget arcu dictum varius duis. Urna duis convallis convallis tellus id interdum velit laoreet id. Eu turpis egestas pretium aenean pharetra magna ac. Aliquet eget sit amet tellus cras adipiscing enim. Ultrices tincidunt arcu non sodales. Fringilla ut morbi tincidunt augue interdum velit euismod in pellentesque. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Gravida dictum fusce ut placerat orci nulla. Egestas purus viverra accumsan in nisl nisi scelerisque. Ornare lectus sit amet est placerat in egestas. Etiam non quam lacus suspendisse faucibus interdum posuere lorem ipsum.</p>
  
  <p>Augue eget arcu dictum varius. Amet consectetur adipiscing elit ut. Ac ut consequat semper viverra nam. Ultrices vitae auctor eu augue ut. Elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. Sed augue lacus viverra vitae congue eu. Nec ultrices dui sapien eget mi proin sed libero enim. Arcu bibendum at varius vel. Faucibus turpis in eu mi bibendum neque egestas congue. Quis hendrerit dolor magna eget est lorem ipsum dolor sit. Et malesuada fames ac turpis egestas integer eget aliquet. Faucibus purus in massa tempor nec. Erat velit scelerisque in dictum. Velit scelerisque in dictum non consectetur. Non diam phasellus vestibulum lorem sed risus ultricies tristique. Quis blandit turpis cursus in hac habitasse. Urna et pharetra pharetra massa massa. Amet commodo nulla facilisi nullam vehicula ipsum.</p>
  
  <p>Maecenas ultricies mi eget mauris pharetra et ultrices. Aliquam id diam maecenas ultricies mi eget mauris pharetra. Fermentum odio eu feugiat pretium nibh ipsum. Suspendisse sed nisi lacus sed viverra tellus. Vel facilisis volutpat est velit egestas. Duis at consectetur lorem donec massa sapien faucibus et molestie. Aliquet bibendum enim facilisis gravida neque convallis a cras semper. Ultrices dui sapien eget mi proin. Id volutpat lacus laoreet non curabitur gravida arcu. Nibh tortor id aliquet lectus proin nibh nisl condimentum id.</p>
  
  <p>Pharetra pharetra massa massa ultricies mi quis. In egestas erat imperdiet sed euismod nisi. Integer enim neque volutpat ac tincidunt vitae semper quis. Ac felis donec et odio pellentesque. Ut enim blandit volutpat maecenas volutpat blandit aliquam etiam erat. Proin fermentum leo vel orci porta non pulvinar neque laoreet. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Tempor orci eu lobortis elementum nibh tellus molestie nunc non. Consequat ac felis donec et odio pellentesque diam. Quisque non tellus orci ac auctor augue mauris augue. Cursus sit amet dictum sit. Pulvinar sapien et ligula ullamcorper malesuada proin libero nunc consequat. Magna sit amet purus gravida quis blandit. Integer feugiat scelerisque varius morbi enim nunc faucibus a. Mauris vitae ultricies leo integer malesuada nunc vel. Pellentesque dignissim enim sit amet venenatis urna. Libero enim sed faucibus turpis in eu mi. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Pretium fusce id velit ut tortor.</p>
  </div>;
};

export default Advantages;
